### ISSUE TITLE
Make it possible to use without authorization in the plex.tv

### ISSUE THREAD

**Issue by Ilia1** [JonnyWong16/plexpy#1520]
### What is your feature request?

Make it possible to use Tautulli without authorization in the plex.tv
Installation requires mandatory plex.tv authorization. But part of the api is available for use without authorization.

**Comment by JonnyWong16** [comment]
Not possible.

**Comment by Ilia1** [comment]
It was not a question.
And it is possible.
Please open the issue and read the link https://github.com/Arcanemagus/plex-api/wiki

**Comment by samwiseg0** [comment]
> It was not a question.
> And it is possible.
> Please open the issue and read the link https://github.com/Arcanemagus/plex-api/wiki

What @JonnyWong16 said is true. It is not possible to have Tautulli function without authorization from Plex.tv. There maybe some API calls that do not require authorization but the vast majority do. Especially the ones that make Tautulli useful. 

Being able to use Tautulli without plex.tv authorization is not something we would like to develop since it does not really make sense to do so.

**Comment by Ilia1** [comment]
I have not logged into PMS and I have access to all api calls without a token.
By skipping the authorization in tautulli, I can see the last added films (only this).
I do not understand what kind of functionality is available only with authorization (server on one computer)

**Comment by Arcanemagus** [comment]
For a non-exhaustive list of the things that require talking to plex.tv (**not** your server), check this file:
https://github.com/Tautulli/Tautulli/blob/master/plexpy/plextv.py

As you have been told multiple times now it is not possible for Tautulli to operate without authorization to your Plex account, if you don't understand the above then please just take our word for it as we will **never** implement this.
