### ISSUE TITLE
Newsletter - "Duplicate" option doesn't copy passwords for Save & Send, but also no warning that the password is not saved

### ISSUE THREAD

**Issue by CBZinger** [JonnyWong16/plexpy#1540]
### Describe the Bug

SMTP password doesn't copy when using Duplicate feature in Newsletter Agent.

### Steps to Reproduce

1. Newlsetter Agents
2. Select Newsletter that's already in the list.
3. Duplicate.
4. Check Sending & Saving
5. Password will display as blank in the SMTP Credentials area.

### Expected Behavior

Password should be copied over when using the Duplicate feature in the Newsletter Agent.  If no password is filled in, there should be a warning stating as such when saving the Duplicate Newsletter.

### Tautulli Version

2.2.7

### Git Branch

master

### Git Commit Hash

5f22ad26ad52fbf7881aac988a59853a2bde9887

### Platform and Version

Darwin 20.6.0 (Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64 - Darwin 20.6.0)

### Python Version

 	3.8.12 (default, Sep 13 2021, 08:26:02) [Clang 11.0.0 (clang-1100.0.33.17)]

### Browser and Version

Firefox 93

### Link to Logs

n/a

**Comment by JonnyWong16** [comment]
This is not an easy problem to solve because the duplication happens in the browser. Basically duplicating is like clicking on "Add a new newsletter agent" while keeping the newsletter configuration modal open so it can save the current values. And the email password is not available in those current values (refer to https://github.com/Tautulli/Tautulli-Issues/issues/172).

1. A new blank newsletter config is added to the database (the same as clicking on "Add a new newsletter agent" in the browser).
2. The _current_ newsletter settings are saved into the new newsletter ID (the same as clicking the "Save" button in the browser).
3. The server side doesn't have any knowledge of the original newsletter ID.

The best I can do is have a warning that Tautulli is not able to copy the email password.

---

Note for myself: This also applies to duplicating any notification agent with a masked password field.
