### ISSUE TITLE
Updating Wiki documentation

### ISSUE THREAD

**Issue by mrvaghani** [JonnyWong16/plexpy#1562]
### Is your feature request related to a problem?

I had Tautulli running inside jail on my FreeNAS box. I ran into some issues and thought it would be helpful to have it in the [Upgrading to Python 3 wiki](https://github.com/Tautulli/Tautulli/wiki/Upgrading-to-Python-3-%28Tautulli-v2.5%29#freebsd--freenas).

Please find the updated wiki with the requested changes [on my fork](https://github.com/mrvaghani/Tautulli/wiki/Upgrading-to-Python-3-%28Tautulli-v2.5%29). I don't think I can do PR for wiki on GitHub yet.

### What is your feature request?

[Updated wiki ](https://github.com/mrvaghani/Tautulli/wiki/Upgrading-to-Python-3-%28Tautulli-v2.5%29)

### Additional Context

Updating documentation to help others upgrade to Python 3

**Comment by samwiseg0** [comment]
Thank you for putting this together. As most of the information seems to be a good addition, I am not quite sure the `pkg: repository meta /var/db/pkg/FreeBSD.meta has wrong version 2` error needs to be added to the wiki. We typically only add things we see most people struggle with and I am not sure this fits into that. 

This seems like it's a system level error and not something specific to updating Tautulli?
From a quick google search of the error. There are plenty of results that show the purposed solution?

**Comment by mrvaghani** [comment]
You're right, this error might be more specific to FreeNAS/jails instead of Tautulli. Feel free to omit whatever you think is not relevant to most people :)

**Comment by JonnyWong16** [comment]
I agree with @samwiseg0.

The scope of the wiki is Tautulli and not a general help page on how to use FreeNAS. Those answers can easily be found by searching elsewhere. I understand that you ran into those issues when trying to upgrade for Tautulli, but that doesn't make those issues related to Tautulli. I don't think I will be adding your changes to the wiki except maybe a small change to explicitly specify the shell for the `clean_pyc.sh` script. Something like `csh clean_pyc.sh` instead of `./clean_pyc.sh`.
