### ISSUE TITLE
bad magic number in 'argparse'

### ISSUE THREAD

**Issue by alexandrecorroy** [JonnyWong16/plexpy#1592]
### Describe the Bug

Cannot start tautulli since last update

/usr/local/etc/rc.d/tautulli: WARNING: $command_interpreter /usr/local/bin/python3 != python
Starting tautulli.
Traceback (most recent call last):
  File "/usr/local/share/Tautulli/Tautulli.py", line 29, in <module>
    import argparse
ImportError: bad magic number in 'argparse': b'\x03\xf3\r\n'
/usr/local/etc/rc.d/tautulli: WARNING: failed to start tautulli

### Tautulli Version

v2.8.0

### Git Branch

master

### Git Commit Hash

/

### Platform and Version

truenas 12.7u

### Python Version

3.8

### Browser and Version

chrome lastest

### Link to Logs

/

**Comment by alexandrecorroy** [comment]
Re-install solved bug

**Comment by thomasglachant** [comment]
Solution : https://github.com/Tautulli/Tautulli/wiki/Upgrading-to-Python-3-%28Tautulli-v2.5%29#notes-2

**Comment by myopenflixr** [comment]
Same issue for me as well.

I ran the script recommended in [https://github.com/Tautulli/Tautulli/wiki/Upgrading-to-Python-3-%28Tautulli-v2.5%29#notes-2](url) but received an error.
`File "clean_pyc.sh", line 4
    echo "This script will remove *.pyc files. These files are generated by Python, but they can cause conflicts after an upgrade. It's safe to remove them, because they will be regenerated."`
                                                                                                                                                                                          ^
`SyntaxError: invalid syntax`

My only solution was to restore a backup prior to the 2.8.0 update.

**Comment by TobiasS1402** [comment]
> Solution : https://github.com/Tautulli/Tautulli/wiki/Upgrading-to-Python-3-%28Tautulli-v2.5%29#notes-2

Thank you very much, had this problem after upgrading inside TrueNAS. Solved it!

**Comment by carlbennett** [comment]
Just stopping by to also add that I experienced this issue.

Tautulli detected an auto-update from 2.7.7 to 2.8.0, it auto-updated, and broke itself with the error message reported in this issue. The bug was present in beta, according to issue #1578, and made it into master (production) since it was misinterpreted as a support issue rather than a bug. I had to rollback to 2.7.7, which resolved the problem. Tautulli runs via python 3.8.10 installed from Linux rpm.

I found this issue thread after searching for others who are having this issue with the new version. If one is auto-updating to 2.8.0, Tautulli should auto-run the pyc cleanup, it was discovered it would be necessary to in 2.8's beta (#1578) and the python dependencies were updated (#1499). The fact it didn't auto-clean pyc and caused this mess is why this is a bug and not a support issue. The expected result should have been hands-off, like it has been for previous updates.

While checked out on 2.7.7, I ran the "contrib/clean_pyc.sh" script, then checked back out master, and restarted Tautulli. It now runs on 2.8.0.

**Comment by samwiseg0** [comment]
> Just stopping by to also add that I experienced this issue.
> 
> Tautulli detected an auto-update from 2.7.7 to 2.8.0, it auto-updated, and broke itself with the error message reported in this issue. The bug was present in beta, according to issue #1578, and made it into master (production) since it was misinterpreted as a support issue rather than a bug. I had to rollback to 2.7.7, which resolved the problem. Tautulli runs via python 3.8.10 installed from Linux rpm.
> 
> I found this issue thread after searching for others who are having this issue with the new version. If one is auto-updating to 2.8.0, Tautulli should auto-run the pyc cleanup, it was discovered it would be necessary to in 2.8's beta (#1578) and the python dependencies were updated (#1499). The fact it didn't auto-clean pyc and caused this mess is why this is a bug and not a support issue. The expected result should have been hands-off, like it has been for previous updates.
> 
> While checked out on 2.7.7, I ran the "contrib/clean_pyc.sh" script, then checked back out master, and restarted Tautulli. It now runs on 2.8.0.

From Tautulli’s perspective this is not a bug. You can search and find that this issue is a widely reported problem with python under certain circumstances. This is a python problem where it does not always cleanup the pyc files. 

So yes it is a support issue. We have created a workaround for the python issue that we will be testing to help avoid this issue in the future.

**Comment by JonnyWong16** [comment]
Tautulli _cannot_ auto-cleanup the `.pyc` files going from v2.7.7 to v2.8.0.

If I add new auto-cleanup code to v2.8.0, you need to _update first_ to get that change. That code _is not present_ in v2.7.7. It doesn't matter if it was in beta or not. So you have a chicken and egg problem. You want the update with the change, but you can't get the update.

And if you say, just run the clean up script when Tautulli first starts up v2.8.0, well Tautulli can't even start, so how is it going to call the script?
