### ISSUE TITLE
Most Concurrent Streams data is incorrect 

### ISSUE THREAD

**Issue by aterriblegamer** [JonnyWong16/plexpy#1641]
### Describe the Bug

A few weeks back I went an looked at my Most Concurrent Stream data and I was very surprised the see it at 74! This is higher than the total number of users that have access to my system...by a lot!

So I took the time to purge out all the data, and for a couple weeks everything was fine. Max was about 7 or so. Today it jumped to 34. No changes to the software, only a reboot of the Plex server.

### Steps to Reproduce

Just run the app....maybe reboot the Plex server. Not sure if that impacts it.

### Expected Behavior

Concurrent data should be realistic

### Tautulli Version

2.8.1

### Git Branch

master

### Git Commit Hash

v2.8.1

### Platform and Version

Windows 11

### Python Version

3.9.7

### Browser and Version

Chrome 97

### Link to Logs

https://gist.github.com/aterriblegamer/5bb70a1bcc060006bcc8bd497c50f8de

**Comment by JonnyWong16** [comment]
You have a bunch of stream that change transcode decision _after_ the stream is stopped. e.g. A stream stops, _and then_ it changes from transcode to direct play (for example). Because the transcode decision event occurs _after_ the stream stopped, it creates a phantom session in the Tautulli database. Whenever Tautulli reconnects to your Plex server, either from restarting Tautulli or restarting your Plex server, it flushes any inactive sessions in the database to the history. Thus you get all those phantom streams occurring "concurrently" as they all get flushed at the same time.

This appears to be a bug in Plex reporting stream events _after_ a stream has already stopped. What Plex clients are you using? Are they using things like "Automatically adjust quality"? Are they transcoding/direct playing? If you look at those "concurrent" streams are they all from the same user/device? Is it all a specific type of media (I noticed it happens with audiobooks in your logs)?

**Comment by aterriblegamer** [comment]
Im not sure how to get that info from the log. To narrow down that gist, the app said I had all those 34 sessions on the 31st. One thing I know did happen on the 31st was a router reboot that morning. Internet hung up and I had to reset at the router. 

If I could force clients to not transcode I would. But Plexs dumb defaults of 720 set on each client makes that a pain to keep on top of with older family that logs in.  For Audiobooks that client is always the same. Only a couple people access those and we all use Prologue. If it looks like that is the culprit. I can take any info here and log something with them.

**Comment by JonnyWong16** [comment]
I suspect you might see a spike in your graphs for January 31st. You can click on the point on the graph to see the history for that day. That might help you narrow down the user/devices/media.

**Comment by aterriblegamer** [comment]
This continues to happen. My current max concurrent stream is 55. Which is higher than the number of users that have access to the server.

**Comment by JonnyWong16** [comment]
Unfortunately there is nothing I can do unless you can provide some clear steps-by-step instructions that I can follow to reproduce the issue consistently. I have no idea what is causing the issue and I'm not even convinced that the problem is with Tautulli yet. No one else has reported a similar problem so it's more likely to be something unique to your Plex/Tautulli setup. What makes your setup so unique, I have no idea.
