### ISSUE TITLE
Import and export watch history

### ISSUE THREAD

**Issue by PedroMorais2610** [JonnyWong16/plexpy#1778]
### What is your feature request?

I think it would be very interesting to have a function to Export and Import users' viewing history.

Example of a situation where this would bring great gains:
 - I have Plex to be shared with family and friends (8 people in total). But whenever I have to format the PC or upgrade the main disk (upgrade to SSD, upgrade to NVME, upgrade size, etc) everyone loses their viewing history.

I've already used the export /import of the files that Plex advises to do, but I think it's not a clean process and it brings garbage behind and I always had the feeling that it doesn't work 100%.

So my idea was to know if there was a possibility to export the history of each user and after formatting the disk or doing a clean installation, import the viewing history.
Or even every x days to make a backup of the history views, because in case some day there is a corrupted file in the plex, all that history is safeguarded.

I don't know if it could be something simple, like an xml file or something.

And by the way, I also want to thank you for your spectacular work!

**Comment by samwiseg0** [comment]
> So my idea was to know if there was a possibility to export the history of each user and after formatting the disk or doing a clean installation, import the viewing history.

This can be accomplished today by backing up and restoring the database. 

> Or even every x days to make a backup of the history views, because in case some day there is a corrupted file in the plex, all that history is safeguarded

Tautulli also does this today. You can configure how many backups to keep and they are done daily. 

I am not sure what benefits there would be in adding something specific to each user. This starts to get complicated as the watch data of a user is tied to actual media in the database so at the end of the day a per user export will need to include the media its tied to in the database. So at that point a database backup is what would be needed. 

It is not clear to me if you mean plex or tautulli in this issue. If you are referring to Plex then the same thing applies. Plex has a database that can be backed up and restored. Preserving watch history.

**Comment by JonnyWong16** [comment]
As @samwiseg0 mentioned, Tautulli already has an automatic/manual backup feature and database import feature.

**Comment by UnviableFriend** [comment]
I'm not sure if I should comment here or make a new issue. But I would like you to reconsider this for other reasons.

I have a music video library on Plex(With close to 10k plays according to tautulli) and am an avid https://www.last.fm/ & https://listenbrainz.org/ user. I would love to be able to export my history for this library to submit to these services since Plex only scrobbles music.

You can see the information the services take through their APIs here that would be good to have in the exports if possible. Last.fm has 3rd party "Scrobblers" that take csv files to scrobble with, and ListenBrainz takes JSON. Though it shouldn't be hard to convert either into the other if only one export format was made available.

https://listenbrainz.readthedocs.io/en/latest/users/json.html#submission-json
https://www.last.fm/api/show/track.scrobble
