### ISSUE TITLE
Unique install id for 3rd party

### ISSUE THREAD

**Issue by beren12** [JonnyWong16/plexpy#1784]
### Is your feature request related to a problem?

Home assistant needs a way to have a unique id for each different Tautulli instance to prevent duplicate setups, to allow more than one Tautulli server be configured.

### What is your feature request?

Have an api to get an install id of some sort that is able to be fetched, and set on install. I believe just about any random number/uuid would work.

### Are there any workarounds?

No

### Additional Context

https://github.com/home-assistant/core/issues/73358 is related.

**Comment by JonnyWong16** [comment]
I fail to see why Tautulli needs to provide an ID or what this has to do with Tautulli at all. Why can't Home Assistant just number them, 1, 2, 3, etc.? How does this solve Home Assistants setup issue if you need to setup Tautulli first before Home Assistant can query Tautulli for an ID? If it's just for the user to provide and ID, then what is preventing you from just giving them unique names like Alice, Bob, Charlie, etc.?

**Comment by samwiseg0** [comment]
I agree with JonnyWong. It is difficult to see a reason to have to have to generate something just for HA when they can just implement a user defined field. 

Another option would be to poll the [Tautulli API](https://github.com/Tautulli/Tautulli/wiki/Tautulli-API-Reference#get_server_id) for the PMS ID and use that.

**Comment by beren12** [comment]
It's an automatic thing where HA's integration gets a unique ID for each service instance. User defined doesn't work as it's there to prevent duplicates. Adding a fetchable uuid seemed like a minor addition but I understand if you don't want to. I was wondering if the pms id would be a good substitute. Thanks for replying.

**Comment by samwiseg0** [comment]
> It's an automatic thing where HA's integration gets a unique ID for each service instance. User defined doesn't work as it's there to prevent duplicates. Adding a fetchable uuid seemed like a minor addition but I understand if you don't want to. I was wondering if the pms id would be a good substitute. Thanks for replying.

The PMS ID should be since its typically one Tautulli instance per plex server.

**Comment by JonnyWong16** [comment]
It's not that I don't want to add it. I don't see how adding it solves the problem.

Isn't that a catch-22? How will Home Assistant query the Tautulli API for an ID in order to set it up if you need to setup Tautulli first in order to query Tautulli?

It's like telling you to call me to get my phone number, but you need my phone number first.

**Comment by beren12** [comment]
I am not certain how it is setup, but "Tautulli does not seem to have a good source for the unique_id. IP address does not qualify." from the linked issue made it sound like it's provided by the remote side.  Or maybe more like "Hey I called this number, what's your name?" :-)

**Comment by JonnyWong16** [comment]
That doesn't help or explain the issue at all. I don't use Home Assistant so you need to explain to me in detail how it retrieves the ID.

This is how I interpret your problem.

1. You already have one instance of Tautulli in Home Assistant.
2. You try to add a second instance of Tautulli in Home Assistant.
3. Home Assistant doesn't let you because it doesn't have "some ID".

This is how I interpret what you want.

1. You already have one instance of Tautulli in Home assistant.
2. You try to add a second instance of Tautulli in Home assistant.
3. _Home assistant allows you to add the second instance???_
4. Home assistant queries Tautulli for "some ID".
    * What's the point of this step if you already got past step 3?

Am I misunderstanding something?

**Comment by beren12** [comment]
As I understand it, the integration fetches a constant value per install from the remote device/service https://developers.home-assistant.io/docs/entity_registry_index/ and uses that to make a registry entry, so entities with the same name can be differentiated from each other

But since tautalli only does 1 plex server at time, the pms id might work well enough for them. I didn't realize it was fetchable.

**Comment by JonnyWong16** [comment]
How does it fetch that value if _it is not set up yet_?

**Comment by beren12** [comment]
It records it as it's doing the setup, it's not something it needs to know before hand, it figures it out as it queries the device/service. Examples in the docs are: Serial number of a device, MAC address, and Unique identifier that is physically printed on the device or burned into an EEPROM

**Comment by JonnyWong16** [comment]
Maybe have one of the maintainers come explain the issue because I don't think you really understand it yourself.

**Comment by JonnyWong16** [comment]
The Plex integration in Home Assistant uses the server ID so I can't see why that won't also work for Tautulli.

https://github.com/home-assistant/core/blob/dev/homeassistant/components/plex/config_flow.py#L217
