### ISSUE TITLE
Request built-in several Python plugins

### ISSUE THREAD

**Issue by Alano-i** [JonnyWong16/plexpy#1785]
### Is your feature request related to a problem?

My tautulli runs in docker.
Push notifications depend on several plugins. Can the container install them by default？
Otherwise, I have to re-install the following installation commands every time I upgrade, which is not very convenient.
`pip install plexapi`
`pip install pypinyin`
`pip install pyyaml`

### What is your feature request?

Request built-in several Python plugins.
`plexapi`
`pypinyin`
`pyyaml`

**Comment by samwiseg0** [comment]
You can include the modules with your script so they do not have to be installed. Otherwise you can create your own custom docker image. 

Python will look in the current directory for the module. Or you can specify one.

https://stackoverflow.com/questions/36459915/is-it-possible-to-use-a-module-without-installing-it-on-your-computer
