### ISSUE TITLE
Watch Together Notifications

### ISSUE THREAD

**Issue by andrewasnodgrass** [JonnyWong16/plexpy#1797]
### What is your feature request?

Request to add a notification trigger for when Watch Together sessions are started with the ability to display what content it is and which users are invited to them under the Text tab.

**Comment by samwiseg0** [comment]
This is not possible since the watch together sessions are negotiated outside of their respective plex servers. Tautulli only captures data that is present on the local plex server instance it is tied to. 

Edit: We investigated adding this in the past. Until plex provides that information on the plex server itself. There is no data that we can gather to determine what is a watch together stream vs a normal stream.

**Comment by andrewasnodgrass** [comment]
That makes sense, thank you.
