### ISSUE TITLE
Newsletter page

### ISSUE THREAD

**Issue by XodgvmXwaCdfTN6Q4DJdsm4a** [JonnyWong16/plexpy#1988]
### What is your feature request?

Would be great if the Newsletter - HTML pages had a listing page for users/admin to click on without having to look for each newsletter email.

**Comment by JonnyWong16** [comment]
Do you mean View Logs > Newsletters Logs > UUID column is a link?

**Comment by XodgvmXwaCdfTN6Q4DJdsm4a** [comment]
not the logs - like a tab or button for users to access old newsletters.

**Comment by XodgvmXwaCdfTN6Q4DJdsm4a** [comment]
question: in "newsletter_85bf8e30.html" how is the "85bf8e30" part generated? I was trying to figure out how to add the previous newsletter as link to the current newsletter.

**Comment by JonnyWong16** [comment]
The UUID is randomly generated.

The logs is a complete list of previous newsletters (with a link to view them). I don't intend to add any way for users to view old newsletters because there is no way to know which users have permission to view which newsletters. This isn't an issue for the admin which is why the links are only available in the newsletter logs.
