### ISSUE TITLE
Graph showing weird data for a specific day

### ISSUE THREAD

**Issue by Weiduus** [JonnyWong16/plexpy#2107]
### Describe the Bug

Hello !

I have more than 700 days of data, and a weird behavior for only one day, where it shows 29 days of TV but only 17 entries in the list.

Is there a way to delete this day in database, or fix the graph ?

### Screenshots

![1](https://github.com/Tautulli/Tautulli/assets/46681880/a24057c8-b2d2-44b5-9055-8019867d1494)
![2](https://github.com/Tautulli/Tautulli/assets/46681880/62373301-d2eb-41a1-8400-f7e0864d8cf8)

### Tautulli Version

v2.12.4

### Git Branch

master

### Git Commit Hash

v2.12.4

### Platform and Version

[Docker] Linux 5.10.0-23-amd64 (#1 SMP Debian 5.10.179-1 (2023-05-12) - Alpine Linux 3.17.4)

### Python Version

3.10.12 (main, Jun 9 2023, 02:29:43) [GCC 12.2.1 20220924]

### Browser and Version

Firefox 116.0.2 (64 bits

### Link to Logs

https://gist.github.com/Weiduus/12be7027f9ec58db8114136a01c9fffd

**Comment by JonnyWong16** [comment]
It looks like Tautulli was shut down while the first 7 streams at the top were still in progress and came back online at 6:36. Since it doesn't know when those streams actually stopped (because it wasn't running) it just assumed they stopped right when it came back. Your logs don't go back to 2023-06-01 so there is no way for me to confirm this assumption. There is nothing you can do about it other than just deleting those entries from your history page.

![image](https://github.com/Tautulli/Tautulli/assets/9099342/64158366-5b17-4dea-8ba8-cb6d65ded806)
