### ISSUE TITLE
Change delimiter of csv Export

### ISSUE THREAD

**Issue by MasothU** [JonnyWong16/plexpy#2153]
### Is your feature request related to a problem?

When exporting the media library as csv file one cannot set the delimiter. Problem is that ',' is for example also part of the summary and therefore when you open the csv file with Excel and use the text to columns feature, data gets lost.

### What is your feature request?

Change/Select delimiter for csv export, e.g. '|'

**Comment by JonnyWong16** [comment]
That's not true. All special characters are properly escaped when the file is generated. It works with quotes and commas.

I tried by

1. opening the csv file with Excel directly,
2. using the Data > From Text/CSV import, and
3. pasting the text and using Data> Text to Columns.

All three methods produced the correct results.

![image](https://github.com/Tautulli/Tautulli/assets/9099342/82780d3b-222f-446b-8aec-1c19c3ac239f)

**Comment by MasothU** [comment]
You are right. I double checked my export and the problem is s.th. different. It seems that a new-line in a summary leads to a new line in the csv file and then the structure is broken for that line and data in that line can't get parsed correctly. 
Have to check tomorrow the summary of that particular file directly on the server.
Seems still to be a bug, although it happens in my export only once

**Comment by JonnyWong16** [comment]
Works fine with line breaks too. Nothing wrong with having line breaks in the csv file, that's perfectly normal.

![image](https://github.com/Tautulli/Tautulli/assets/9099342/d168d170-a19b-4d0f-9f3b-462fb08f601d)

![image](https://github.com/Tautulli/Tautulli/assets/9099342/1cedc261-f6fa-463c-bf0e-180cf6c665c1)

It obviously won't work if you just copy and paste the text into Excel. Don't do that.

I'm closing this issue because there is nothing else needed here.
