### ISSUE TITLE
Stuck at auth page after upgrade to 2.13.4

### ISSUE THREAD

**Issue by CRFC11** [JonnyWong16/plexpy#2215]
### Describe the Bug

Tautulli starts up but then requests authentication (I authenticate with Plex login) everything seems to go through then it refreshes and brings us back to the authentication page.

### Steps to Reproduce

Start Tautulli
go to Tautulli web page (localhost:8181 for me).
Sign in using Plex Auth

### Expected Behavior

Authentication should parse then I'm able to access Tautulli

### Tautulli Version

2.13.4

### Git Branch

Master

### Git Commit Hash

NA

### Platform and Version

Windows 10 64Bit

### Python Version

NA

### Browser and Version

Edge 119.0.2151.97

### Link to Logs

unable to find/create logs

**Comment by samwiseg0** [comment]
Without logs we will be unable to troubleshoot this issue. Please refer to the [FAQ](https://github.com/Tautulli/Tautulli/wiki/Frequently-Asked-Questions#general-q14) on where to get your logs

**Comment by MagicalCrib** [comment]
I also see this, in the previous version I had issues only in Firefox, not I have the issue also in Chrome. Opened this ticket yesterday for my issue: https://github.com/Tautulli/Tautulli/issues/2212
With the _Remember me_ checked or unchecked, I can't login.

**Comment by MagicalCrib** [comment]
Ok it's working now. Looked at the commits, and found the issue was probably due to a cookie issue that was expiring too fast, so I deleted all cookies from Firefox and Chrome and it now works on both.

**Comment by siggijarl** [comment]
Happened to me as well, and clearing cookies did not fix it.
Then realized I could log in if I used the IP instead of the hostname as the url.

Logs don't show anything other than the auth being successful, even when the login page just reloads and doesn't let you in.
`2024-01-01 01:01:51 - DEBUG   :: CP Server Thread-5 : Tautulli WebAuth :: Admin user 'si********l' logged into Tautulli using form login.`

**Comment by MagicalCrib** [comment]
This issue is back for me. I tried to access Tautilli and got the login page, and it was not accepting my Plex login neither my Tautulli login, with or without the option to remember the login.
I cleaned my cookies and was was able to login, but after around 5 minutes I got to the login page again, with the same difficulties to login.

I can only see the following lines in the log:
```
2024-02-05 11:35:57 - DEBUG :: CP Server Thread-13 : Tautulli WebAuth :: Admin user 'Se********m' logged into Tautulli using Plex OAuth login.
2024-02-05 11:36:07 - DEBUG :: CP Server Thread-10 : Tautulli WebAuth :: Admin user 'myuser' logged into Tautulli using form login.
```

**Comment by samwiseg0** [comment]
@modem Please include your entire logs. Also please check the browser console for errors or anything of note.

We are unable to reproduce this issue nor have we ran into this issue.
