### ISSUE TITLE
Question about i18n Support

### ISSUE THREAD

**Issue by sqkkyzx** [JonnyWong16/plexpy#2341]
### Is your feature request related to a problem?

I noticed that there is an i18n branch, but the last commit was 3 years ago. I would like to know if it is currently possible to switch to languages other than English?

### What is your feature request?

Are there any plans to support i18n in the main branch?

**Comment by JonnyWong16** [comment]
Nope. I started then quickly realized that it's an overwhelming amount of work. Trying to add translations to something that didn't plan on it from the beginning is too much work. There are no plans to add translations anytime.

**Comment by sqkkyzx** [comment]
> Nope. I started then quickly realized that it's an overwhelming amount of work. Trying to add translations to something that didn't plan on it from the beginning is too much work. There are no plans to add translations anytime.

If I create a localized version for a specific language (I mean Chinese) by modifying the files directly, can I submit a Chinese localization branch for the project, and could you assist in building the container image? Or would you prefer that I maintain it only in my fork? I have already started working on this and plan to gradually improve it in my spare time. @JonnyWong16

**Comment by unLieb** [comment]
Following up on this since it's been about two years — I understand the original concern about the amount of work involved, and that's completely valid for how development tooling looked back then.

Since then, AI-assisted coding has moved a lot in terms of what's realistically doable as a solo/community effort — mechanically extracting and wrapping strings across templates, setting up a gettext/Babel pipeline, and producing a first translation pass is much less daunting now than it would have been in 2021 or 2024.

I'd like to take a shot at a German localization, partly because I've been a long-time Tautulli user, and partly because a competing tool (Tracarr) now offers German out of the box, which made me want to see if this is still off the table here.

Rather than asking for a commitment upfront, I'd plan to build this out on a fork first (i18n infrastructure + German translation) and show a working proof of concept — so you'd be able to judge the actual diff and maintenance burden rather than a hypothetical one. Would you be open to taking a look if it turns out clean and doesn't get in the way of your regular development?

No worries if the answer is still no — just wanted to check given the time that's passed and how things have changed.
