### ISSUE TITLE
Can we separate Other Videos from Movies in History?

### ISSUE THREAD

**Issue by ArniVidar** [JonnyWong16/plexpy#2444]
### What is your feature request?

This may just be a problem with Plex it self, but if not, could we please get the Other Videos libraries sorted out of the Movies filter in the History? Plex has 5 library types, but Tautulli only has 3 of them. :)
I have a library that specifically sees various types of video files and quite a lot of files going in and out of there (watched, then deleted), but they are all shown in History as Movies. This is both annoying and simply wrong, and makes the Movies filter pretty much usable because there are FAR more files watched from that library than the Movie libraries. 😄 

Does the API even distinguish between Movies and Other Videos? 

![image](https://github.com/user-attachments/assets/3e555763-5337-43c2-b690-2e645a178cab)

**Comment by JonnyWong16** [comment]
An "Other Videos" library is just a "Movies" library with the personal scanner/agent preselected for you. You can create a "Movies" library then manually change the scanner/agent and it will be identical to "Other Videos". Because these two are just movies library under the hood, Plex reports everything as a movie.

**Comment by ArniVidar** [comment]
Figured that might be the case. Thanks!
